### ISSUE TITLE
Query composition

### ISSUE THREAD

**Issue by tlvenn** [apollostack/react-apollo#100]
Similarly to how query composition works in Relay, it would be neat to be able to compose queries using fragments defined in child components.

A good overview on how Query composition is handled by Relay:
> http://stackoverflow.com/questions/33095479/how-does-query-composition-work-between-a-container-and-a-route-in-relay

**Comment by tlvenn** [comment]
Another interesting read: https://github.com/facebook/relay/issues/309

**Comment by jbaxleyiii** [comment]
@stubailo I'd love to get your thoughts on this as well

**Comment by stubailo** [comment]
Just shipped some docs about this! http://docs.apollostack.com/apollo-client/fragments.html Perhaps we should add something React-specific to the docs as well, like attaching fragments as static properties on the components?

**Comment by jbaxleyiii** [comment]
@stubailo I'm planning on adding an API for attaching fragments to components in the 0.4.0. I still need to work on the API. @tlvenn or @stubailo do you have a sample where this would be helpful?

**Comment by stubailo** [comment]
Right now the most helpful situation for me is if I have a query and a mutation that updates the query. Since I need to fetch the same fields in both, I'd like to use a fragment.

I think one thing that could be sad though is if you have to make a container or something heavy just to attach a fragment. I feel like ideally it could just be a static React component property or something?

**Comment by jbaxleyiii** [comment]
Related: https://github.com/apollostack/react-apollo/issues/122

**Comment by jbaxleyiii** [comment]
Closing in favor of common discussion in #140
