### ISSUE TITLE
Guidance: Avoiding unnecessary re-renders

### ISSUE THREAD

**Issue by nevir** [apollostack/react-apollo#101]
So, I'm a bit new to the GraphQL/Apollo world, and am a bit confused about the right approach to structure components to avoid unnecessary re-renders.  Particularly when you're also juggling some state in traditional redux (e.g. frequently making use of _both_ `mapQueryToProps` and `mapStateToProps`)

In the traditional redux world, you can just do a shallow comparison over your props, and call it a day (because object identity is preserved).  However, with Apollo/GraphQL, the client ends up generating new objects each time a query result is processed.  

Traditionally, we'd take the approach of mostly only using `@connect` at high level components, and having them pass props through the component graph from there.  But, in a GraphQL world, that gets blown out of the water (I think?) due to the query result being rebuilt every time anything in it changes.  We could potentially do deep comparisons in `shouldComponentUpdate`, but that seems overkill.

Or, another approach is to `@connect` at most components that require state, and just trust that the `@connect` wrapper only triggers updates when necessary.  But that also seems pretty heavy, as that's a lot of unique queries being built and watched?  Maybe #100 is the solution?

Are there other ways I should be approaching this?

**Comment by stubailo** [comment]
Are unnecessary re-renders currently a problem for you?

Ideally, we can get apollo client and react-apollo to the point where you don't have to worry about this at all because the GraphQL layer will handle avoiding rerenders for you, based on the fields you are using. We already do some of this, for example we avoid rerenders when non-apollo Redux state changes.

Would such an approach work for you?

@Poincare is starting to work on performance soon, perhaps he can pitch in.

**Comment by nevir** [comment]
> Are unnecessary re-renders currently a problem for you?

Currently nope - I'm still exploring switching over to apollo for several relatively complicated apps.  This is currently speculation on my part - and I just want to make sure I'm structuring these apps in a way that won't hamper any perf improvements you guys ultimately add

---

> Ideally, we can get apollo client and react-apollo to the point where you don't have to worry about this at all because the GraphQL layer will handle avoiding rerenders for you, based on the fields you are using. We already do some of this, for example we avoid rerenders when non-apollo Redux state changes.
> 
> Would such an approach work for you?

I think so!  In that world, should I prefer to `@connect` most of my components (vs composing queries a.la. Relay)?

**Comment by stubailo** [comment]
We're trying to achieve a world where it doesn't matter what patterns you use to connect the data - IMO it should be fast regardless of whether you have a lot of small queries or one big one.

I think fragments should only be necessary for nested data fetching, not as a required thing to increase performance. This is why we built the batching feature, which gives you a lot of the same benefits as fragments, but without the hassle: http://docs.apollostack.com/apollo-client/network.html#query-batching

**Comment by Poincare** [comment]
Btw, this should be fixed now; we have both query composition through fragments and only deliver results to query observers when there is a change in results. I wrote [this](https://medium.com/apollo-stack/snappier-uis-with-apollo-client-graphql-bffab0b52b79#.hr7uzso1y) that describes some of the perf. related work we've been doing.

**Comment by MrLoh** [comment]
@Poincare @stubailo thanks for your explanations. I’d also be very interested in understanding the performance impacts better. 

I’m building a React native app, so performance is much more critical and harder to manage. Unfortunately this is a very unexplored topic and it’s hard to find information. With redux at least I understand what causes rerendering and how to leverage tools like reselect and cached callback functions to improve performance (without deep comparisons). With Apollo I don’t understand what causes rerenderings. And it also has to be balanced against other concerns like offline capabilities. E.g. I might want to fetch a bit more data on a list view so it’s already available for a detail view but now I’m subscribing to unnecessary data that might cause unnecessary rerenderings, probably not a good idea. I also don’t know wether transforming the query shape with the `props` option is a good idea. Probably it is quite problematic especially with deeper nested props and when using directly returning arrow functions that create a new object every time. 

In React native the situation is especially sensitive because (especially here in germany) many people use older phones (iPhone 5s are still quite common). And another giant issue in react native performance when coupled with state subscriptions like redux and Apollo is that in a React native application not just the currently visible screen will be rendered, but the full stack of screens you are currently on and the other main tabs of your app (no matter wether you use react-navigation or react-native-navigation). Unfortunately the connect and graphql functions are not optimized for that since they assume that every mounted component should update when new data comes in. You are only left with the option of putting a should update check after the connect or graphql HOC to prevent rerenderings when the screen is currently not visible, but if graphql HOC does some heavy lifting for preventing rerenders internally (like a deep equality check) there is no way in which I can stop that, because I have no influence on wether the subscription is triggered or not. 

All that is just to say the performance optimization might be pretty unproblematic in web but is very hard in React native and has very different needs and often requires more granular controls. Currently there is very very little information about how Apollo’s internal reselect mechanism works (or at least I can’t find it). And that makes it very hard to build a good architecture and avoid pitfalls especially for React native apps. 

It would be great if performance was just something we wouldn’t have to worry about but for complex React native application that’s probably never gonna be the case and we need better understanding of the trade offs and functionality inside Apollo to optimize the performance of apps.
