### ISSUE TITLE
Warning related to setState in componentWillMount when doing SSR in v0.4.7

### ISSUE THREAD

**Issue by raymondsze** [apollostack/react-apollo#167]
Current codes of react-apollo seems directly call the component's componentWillMount and render functions which seems not behave similar to `ReactDOMServer.renderToString(<Component />)`

I am playing react-apollo with material-ui.

There is no WARNING when I call `ReactDOMServer.renderToString(<Root />)`
But there is WARNING when I call `getDataFromTree(<Root />)`
My Root Component render function is simple
just
```
<div>
  <TextField />
</div>
```
Content of TextField: https://github.com/callemall/material-ui/blob/0.15-stable/src/TextField/TextField.js

You can see `setState` is called in `componentWillMount` that would trigger the warning, however there is no warning when using `ReactDOMServer.renderToString` instead.

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the TextField component.
`

**Comment by jbaxleyiii** [comment]
@raymondsze the fix for this and I think #166 are going to require a custom react rendered to be written. I'm planning on working on this soon! In the interim, I think removing the `componentWillMount()` call and noting that not everything currently works on SSR is the best option.

Writing the renderer is the top priority for this library so it should be done pretty soon!

**Comment by jbaxleyiii** [comment]
fixed with #205 which will be out shortly
