### ISSUE TITLE
Server rendering and hydrating apollo store

### ISSUE THREAD

**Issue by gauravtiwari** [apollostack/react-apollo#22]
Hey @stubailo I am exploring the new apollo client with Rails (https://apollo-rails.herokuapp.com/) and was wondering - how the client supports hydrating the store without redux. I see it's react-container is inspired heavily from redux and redux does offer hydrating store while creating the store, but not sure how this works with react-apollo (basic apollo version)? `let store = createStore(todoApp, window.STATE_FROM_SERVER)`

**Comment by jbaxleyiii** [comment]
@gauravtiwari the Apollo client offers a reducer to add to your existing redux reducers before creating the store. If you add that then pass the store to the provider, you should be able to rehydrate. Check out the docs on using with Apollo with redux. 

Store rehydration is fantastic isn't it

Let me know if you run into any issues!

@stubailo it may be cool to add in the ability for the default store go be rehydrated for those not using redux aside from the client

**Comment by gauravtiwari** [comment]
Thanks @jbaxleyiii for swift reply. Yeah I know, but was wondering if it would work without using redux. Yeah, it would be handy for a lot of folks who are not using Redux, plus basic apollo version does use Redux under the hood to track the state so, would be super cool 👍

**Comment by jbaxleyiii** [comment]
@gauravtiwari that's a fanatic idea the more I think about it. I'll add that in this evening and let you know when it's there!

**Comment by gauravtiwari** [comment]
Awesome @jbaxleyiii - this feature would be super handy for Server rendering.

**Comment by jbaxleyiii** [comment]
@gauravtiwari I am curious, it's been awhile since I've done anything with rails. My thoughts would be to add something like `getStore` method that returns the data from the internal store. Then on the client see if there is a `window.__APOLLO_STORE__`  and pass that to rehydrate?  Would that be sufficient for you? Then your app could get the data and pass it to the client in a script tag?

This would make it easy to add fast render support for meteor apps and SSR support for plain react apps as well. Even embers new SSR support should be able to make use of it

**Comment by gauravtiwari** [comment]
@jbaxleyiii Yup, it would work. Yes, it would make sense to keep the setup versatile so, something like `__APOLLO_STORE__` bound to window object would be super easy to use for any setup. 

I am using this approach though: https://github.com/gauravtiwari/apollo_on_rails/blob/master/app/views/posts/show.html.erb#L2. You see I am passing a hydrated prop using this helper function on rails. This renders an empty div tag with `data-attrs`, and then within component I am using the id here for example: https://github.com/gauravtiwari/apollo_on_rails/blob/master/app/assets/javascripts/components/posts/show.es6.js#L41

Then dynamic rendering based on `data-attrs`: https://github.com/gauravtiwari/apollo_on_rails/blob/master/app/assets/javascripts/renderer.jsx#L25

So, something like this would also work for hydrating the apollo store.

**Comment by jbaxleyiii** [comment]
Awesome, thanks for the examples! I'll knock out this functionality this evening and let you know

**Comment by jbaxleyiii** [comment]
Note to self: `client.store.getState()` should work or we can create a shortcut with `client.getState()` but it seems unnecessary

**Comment by jbaxleyiii** [comment]
Coressponding PR: https://github.com/apollostack/react-apollo/issues/22

**Comment by gauravtiwari** [comment]
Hey @jbaxleyiii I tried implementing this, and looks like it doesn't works with `react-apollo`. Does this function needs to be exposed to `react-apollo` package?

#### Implementation on server: 

`const initialState = client.store.getState()` this gives me undefined (`store isn't available`) initially. For example, here is how I am trying to set it up on server: 

```js
  const client = new ApolloClient({
    initialState: props, // props is passed via data-attrs
  });

  const reactElement = createReactElement(name, props);

  htmlResult = ReactDOMServer.renderToString(
    <Provider client={client} children={reactElement} />
  );
``` 

The props does show up separately in the { `client` and `props` } object within the component, but doesn't work with existing store.  The component renders fine, but it makes the query to server and also throws following error in console after render: `Unexpected key "post" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: "apollo". Unexpected keys will be ignored.`

I guess we should pass the `prop/initialstate` to result object, so that the it matches with the required `query` and then returns the same result object. See screenshot: 

![screen shot 2016-04-21 at 22 40 40](https://cloud.githubusercontent.com/assets/771039/14722005/1a533574-0812-11e6-949c-8671534a9f82.png)

`post` is Passed as separate object (this is from server): 

![screen shot 2016-04-21 at 23 00 26](https://cloud.githubusercontent.com/assets/771039/14722588/e2763496-0814-11e6-83d5-eb3b8cd3489e.png)

**Comment by stubailo** [comment]
Can you file the exact same thing in a new issue? I don't think these closed threads are a great place to discuss stuff.

**Comment by gauravtiwari** [comment]
@stubailo Could we reopen this issue may be (avoid duplication)?

**Comment by jbaxleyiii** [comment]
@gauravtiwari so I think I misunderstood your build out. It looks like you are rendering data as props on different container components yes? and passing those through to `react-apollo` as props?

With redux, store rehydration happens when you actually create the store itself. The way the change was written was to support rehydration from a fully generated store that was on the server.

Steps on the server:

1. Create new empty client
2. Render the react app to string (this should populates the store with queries)
3. Get the filled store via `client.store.getState()`
4. pass the filled store to the client in a template tag or script tag

Steps on the client:

1. Retrieve the passed store
2. Create new apollo client with store as the initialState

A few gotchas:

The react-apollo component doesn't currently expose a static `fetchData` method on the components. I would like to add this but need to think through the best way to do it since it relies on parent props. So depending on how you are rendering your tree / getting data, you may have an empty store sent to the client.

The `initialState` has to be a an object with the top level key of `apollo` or whatever else you named the redux key. Redux will try to pass the initial state to all of the reducers (in this case the internal apollo reducer) and it will break it up based on the key (e.g. apollo reducer only gets data from the apollo key)

An example of our SSR process: https://github.com/NewSpring/meteor-react-router-ssr/blob/master/lib/server.jsx#L274-L309

I'll write a sample SSR + apollo + react app tonight and outline the critical parts.

Sorry for the confusion! Hopefully we can still make this work great for you!

**Comment by gauravtiwari** [comment]
@jbaxleyiii I see, how it may work work fine for full-stack JS environments, but this would be hard to achieve (atleast hacky) for other non-js server side framework. It's achievable, but very hacky and hard.  I guess, we need a function that allows to inject the required data wherever possible, possibly within initial state that takes the initial data as argument and merge it with store.

**Comment by gauravtiwari** [comment]
No worries, lets see how possibly we can make it work for all solutions (JS or Non-js server environments) :)

**Comment by jbaxleyiii** [comment]
Server rendering and hydrating the store is being added for a first run via #83 and most of the discussion is in #54. Closing this in favor of the other issue

**Comment by carobeta** [comment]
Hi @ jbaxleyiii! I have problems with apollo-client and redux-persist integration.
Can you give me an example of rehydration? I can't understand how to rehydrate the state of apollo

Thanks!!

**Comment by jbaxleyiii** [comment]
@carobeta have you take a look at http://dev.apollodata.com/react/server-side-rendering.html#store-rehydration?

I'd be interested to know if apollo works with redux-persist!
