### ISSUE TITLE
Cannot find module 'recompose/compose'.

### ISSUE THREAD

**Issue by Axure** [apollostack/react-apollo#279]
## Steps to Reproduce

Just import `react-apollo`.

### Buggy Behavior

```
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/react-apollo/index.d.ts
[0] (3,21): error TS2307: Cannot find module 'recompose/compose'.
```

### Expected Behavior

No error.

### Version
- apollo-client@0.4.21
- react-apollo@0.5.11

**Comment by Axure** [comment]
It seems that delete the definition for `recompose/compose` in `react-apollo/typings.d.ts`, and modify the import statement in `react-apollo/index.d.ts`ex.d.ts` resolves the error.

**Comment by stubailo** [comment]
Send a PR?

**Comment by Axure** [comment]
@stubailo I wonder if is only a problem of mine.

**Comment by stubailo** [comment]
Neither I nor @jbaxleyiii use this package with an app written in TypeScript, so I don't have an easy way to test this.

**Comment by vlasenko** [comment]
I have the same problem too with TypeScript app

**Comment by vlasenko** [comment]
@Axure Could you actually submit Pull Request for your patch, so that guys could merge it into react-apollo?

**Comment by migueloller** [comment]
Apollo already uses Redux internally. Why not just use Redux's compose instead?

**Comment by vlasenko** [comment]
@migueloller It's not the topic of this issue. Current issue is about error when using react-apollo in TypeScript apps. And it has trivial solution. What is best to use - compose from Redux or from Recompose is a different topic

**Comment by vlasenko** [comment]
So, this change fixes the error:
https://github.com/vlasenko/react-apollo/commit/cbdee3a24496769b25ffba3f966ef531452a15db
However it's not a proper fix, because lint complains on this line.

In case someone in a hurry working on TypeScript app and faces this error,  you can use 
npm i -S git+https://git@github.com/vlasenko/react-apollo.git
at the moment as a temporary workaround, until this issue will be properly resolved.
