### ISSUE TITLE
How can we test react-apollo components?

### ISSUE THREAD

**Issue by HriBB** [apollostack/react-apollo#311]
Hey. I'm trying to figure out how to test `react-apollo` components. Are there any good examples out there? There's nothing in the docs.

I want to test queries and mutations. Looking at the [Pokemon.test.js](https://github.com/apollostack/react-apollo/blob/master/examples/create-react-app/src/Pokemon.test.js) example, but it uses `create-react-app`, which has testing setup through `react-scripts`.

Can someone please provide an example. Thanks

**Comment by jbaxleyiii** [comment]
@HriBB `react-scripts` uses `jest` under the hood. Everything else should be the same! I'll try and update the meteor and react-native projects. Although the test-utils imported by that file can be used with any testing framework!

**Comment by HriBB** [comment]
Ok, thanks!

**Comment by viridia** [comment]
@jbaxleyiii In your response above, you say "the test-utils imported by that file can be used with any testing framework", but I'm having a lot of problems doing just that.

I'm attempting to use the test-utils with react-enzyme, and I'm able to mock the component - except that the component renders with the wrong data. The call to react-enzyme's 'mount()' function returns before the promise in the mocked network provider has resolved, so the component gets rendered once with an empty result, and then again with the mocked data - unfortunately too late since by that time all my assertions have tried to run and failed.

If there was some way I could wait on the promise before running my assertions this would work, but the promise is buried deep inside several scopes and is thus inaccessible. Can you think of a way that I could delay my assertions until the component has had a chance to render with the actual mocked data?

**Comment by goldo** [comment]
here's a link about what we are doing:
https://github.com/apollographql/apollo-test-utils/issues/30
@viridia it should not solve your problem, but it might avoid it
Anyway, tell me what you think

**Comment by Didericis** [comment]
I put together a guide for testing in 2.0 after looking through a bunch of other threads/blog posts on this and playing around with different approaches: http://blog.dideric.is/2018/03/18/Testing-apollo-containers/
