### ISSUE TITLE
Expose subscription.unsubscribe in prop object

### ISSUE THREAD

**Issue by jbaxleyiii** [apollostack/react-apollo#32]

**Comment by stubailo** [comment]
What would this be used for?

**Comment by jbaxleyiii** [comment]
@stubailo if you are polling, you may want to manually stop after a certain number of changes, or after a certain data change

**Comment by stubailo** [comment]
Hmm, unsubscribe isn't really the right thing here though, because then you also wouldn't get optimistic updates or refetches from other queries. I was thinking the react integration would internally create a new query handle on a `stopPolling` call, or maybe use an argument passed into `mapQueriesToProps` to change the `pollInterval` argument?

**Comment by jbaxleyiii** [comment]
@stubailo gotcha, okay I'll rework this PR some

**Comment by jbaxleyiii** [comment]
Sorry, the polling API to allow for stopping the polling without stopping the query
