### ISSUE TITLE
Variables from ownProps should automatically refetch

### ISSUE THREAD

**Issue by mmmdreg** [apollostack/react-apollo#358]
## Steps to Reproduce

```js
graphql(someQueryById, {
  options: (props) => ({
    variables: {widgetId: props.params.widgetId}
  })
})
```

### Buggy Behaviour

If the props change, the query hits the server with the variable from the old prop. Using things like skip and refetch don't make a difference. The only way to force it to use the new variable is to unmount and remount the container. So far, it has been mostly possible to structure my components in a way that I can unmount/mount, but the current behaviour does not make sense from a react point of view. What should render should depend on current props, not the original props at the time a component was mounted. 

### Expected Behavior

It should automatically refetch with updated props/variables. 

### Version
- apollo-client@0.5.10
- react-apollo@0.6.0

**Comment by tmeasday** [comment]
Hi @mmmdreg this is very surprising as this is of course how it is designed to work (and there are multiple tests for this exact behavior).

Have you tried loggin in the `options` function to check if it's getting called?

**Comment by mmmdreg** [comment]
Yes. I can see the new prop in the option, but the query is never performed with the new variable. 

To give some context, in a single container, I have a mutation and a query. Initially the URL has no id in it. The mutation submits a form to the server and gets back an id. If the call is successful, it does a router.push and adds the id to the URL, making the query pull the details. 

I have a back button, where I can submit the form again and get back a new id, again pushed to the url. I can see the mutation return the new id, but the query is not run. If the mutation is set to refetch the query, the query is run with the old id. 

The workaround is to put the query in a container at the /:id route, so it is unmounted every time the id is removed. But this should not be necessary. 

I've seen this issue repeatedly in different parts of my app so I don't believe it's a localized issue.

**Comment by tmeasday** [comment]
In the "back" case is the second mutation returning a new `widgetId` or an old `widgetId` that had been used before?

If so, could it be that apollo is simply caching the old value of the query. 

If you are setting `refetchQueries` on the mutation, it may be too soon as the new variable hasn't propagated via the router change yet.

**Comment by tmeasday** [comment]
What happens if you set `forceFetch` on the query?

**Comment by mmmdreg** [comment]
It's always a new widgetId. Forcefetch is the same behaviour as refetch - it makes it request with the old prop.

**Comment by jbinto** [comment]
I am running into a problem that seems very similar, though subtly different. (This is probably too vague and I will need to do an isolated repro case, but here goes nothing):

* When I click a button, I issue a mutation. I get an ID back (e.g. `id=1`).
* A polling query starts (since the value of a `skip` became false). `options` is called with `ownProps`, and that has the ID from the mutation (e.g. `id=1`).
* Polling begins, and network inspector shows the right query (e.g. `id=1`)
* After the polling query changes some state, we flip `skip` again and polling stops.
* All is well at this point. 

But, if I click the button again, this happens:

* The mutation is issued. I get a new ID back (e.g. `id=2`)
* A polling query starts (since the value of a `skip` became false). `options` is called with `ownProps`, and that has the ID from the mutation (e.g. `id=2`).
* Polling begins, and network inspector shows the **WRONG** query, using the previous variables. (e.g. `id=1`)
* This breaks other things in my app because it was not expecting a result for `id=1` but for `id=2`.

I'm using two `graphql` HOCs, `withMutation` and `withPollingQuery`. I composed them like `withMutation(withPollingQuery(Component))`. (Is this ok? I always worry about the order I compose things in)

I will try to get an isolated repro case. 

`forceFetch` doesn't make any difference.

**Comment by tmeasday** [comment]
@jbinto I suspect this might be a different issue (not that I have much of an idea about what could be causing @mmmdreg's issue). In your case it sounds like when the variables change to a polling query (alongside skip changes?) the polling part can get stuck w/ the old variables.

**Comment by jbinto** [comment]
OK, thanks. When I get an isolated case I will open a new issue.

**Comment by tmeasday** [comment]
@mmmdreg is it possible that changing skip + variables at the same time is the issue here? That would fit with @jbinto's reproduction.

Although you mentioned "Using things like skip and refetch don't make a difference".

**Comment by tmeasday** [comment]
@mmmdreg are you still seeing this issue? I'd like to close it if it was fixed by https://github.com/apollostack/react-apollo/issues/376 or figure out a reproduction if not.

**Comment by mmmdreg** [comment]
It seems to be okay right now with apollo-client 0.5.21 and react-apollo 0.7.2. Thanks.
