### ISSUE TITLE
GraphQL errors are not correctly passed to component props

### ISSUE THREAD

**Issue by davidye** [apollostack/react-apollo#378]
With apollo-client@0.5.23, it appears that:

`(new ApolloError()) instanceof ApolloError // false`

This is causing errors to be thrown from here:

https://github.com/apollostack/react-apollo/blob/02fe991c8645c939e5d41587c76c447c7081e02f/src/graphql.tsx#L381

Here's the relevant code which changed recently in apollo-client:

https://github.com/apollostack/apollo-client/blob/master/src/errors/ApolloError.ts#L3

### Version
- apollo-client@0.5.23
- react-apollo@0.70.1

**Comment by tmeasday** [comment]
@helfer should we be using `isApolloError`?

**Comment by helfer** [comment]
@tmeasday as you probably saw in the code I ended up adding that function because I couldn't figure out why after updating TS `new ApolloError() instanceof ApolloError === false`. It's not exported though, so if it should be fixed quickly, I suggest just checking for the `graphqlErrors` property on the error, and then changing it to `isApolloError` later.

**Comment by davidye** [comment]
@helfer it's probably because extending built-in classes cannot be properly subclassed with transpilers, see:

http://stackoverflow.com/questions/33832646/extending-built-in-natives-in-es6-with-babel
https://github.com/babel/babel/issues/1424

**Comment by tmeasday** [comment]
I think a quick fix is warranted here if someone wants to take a look.
