### ISSUE TITLE
0.7.3 has issues with TypeScript typings

### ISSUE THREAD

**Issue by alexgorbatchev** [apollostack/react-apollo#395]
### Buggy Behavior

```
    ERROR in project\node_modules\react-apollo\lib\graphql.d.ts
    (4,10): error TS2305: Module ''graphql'' has no exported member 'DocumentNode'.

    ERROR in project\node_modules\react-apollo\lib\graphql.d.ts
    (4,24): error TS2305: Module ''graphql'' has no exported member 'FragmentDefinitionNode'.

    ERROR in project\node_modules\react-apollo\lib\graphql.d.ts
    (2,1): error TS2688: Cannot find type definition file for 'graphql'.
```

### Expected Behavior

Should see no warnings. `<= 0.7.2` works fine

### Version
- apollo-client@0.5.26
- react-apollo@0.7.3

**Comment by stubailo** [comment]
Oh dang, @jbaxleyiii we should have published the typings as 0.8, since it's definitely a breaking change for TypeScript users.

@alexgorbatchev you can fix this by installing @types/graphql and upgrading to the newest version of Apollo Client I think. We accidentally published a breaking change as a patch version.

**Comment by helfer** [comment]
I'm going to fix this by re-releasing 0.7.2 again as 0.7.4 and then releasing what's currently 0.7.3 as 0.8.0.

**Comment by stubailo** [comment]
@helfer you're done right? @alexgorbatchev can you verify that 0.7.4 resolves your issue?

**Comment by helfer** [comment]
Discussion in #398 now. The version to install should be 0.8.1.
