### ISSUE TITLE
Should getDataFromTree return data

### ISSUE THREAD

**Issue by choonkending** [apollostack/react-apollo#409]
## Steps to Reproduce

In the documentation for [Server Side Rendering](http://dev.apollodata.com/react/server-side-rendering.html) for the usage of **getDataFromTree**, it returns a `Promise<void>`.

```js
getDataFromTree(app).then(() => {
  const content = ReactDOM.renderToString(app);
  const initialState = {[client.reduxRootKey]: {
    data: client.store.getState()[client.reduxRootKey].data
  }};
  . . .
});
```

### Expected Behavior

This is more of a design question. 

Without looking too deeply into the implementation, I expected a signature more similar to the following

```js
getDataFromTree(app).then(data => {
    const content = ReactDOM.renderToString(app);
    const initialState = { apollo: data }; 
});
```

My question is:
1. Can we return `data` that is `client.store.getState()[client.reduxRootKey].data`?

### Version
- apollo-client@0.5.25
- react-apollo@0.7.2

P.S. Love the work you've all done! Thanks!

**Comment by tmeasday** [comment]
Hey @choonkending, we initially did have it doing (something like) that, but it's tricky to do it in a reasonable fashion because all we are passed is an element tree, and we'd have to reach in an find the client to call that on.

There are edge cases; like what if there are two different clients and two different `ApolloProviders` inside the render tree for some reason?

You can call `client.getInitialState()` by the way. I'll update the docs

**Comment by choonkending** [comment]
Whoa! Thanks for that lightning quick response! 

Fair enough. Did not consider the need for nested `ApolloProviders` with different clients. 

Closing the issue!
