### ISSUE TITLE
How to redux-form? Or how to copy the Apollo result to redux store.

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/react-apollo#56]

**Comment by tomitrescak** [comment]
Hi,I really like the redux-form project. I was wondering how could I make it work with Apollo redux? My issue is, that form values need to be preloaded from the store. How do I access the store values returned by Apollo? Will the disappear if I perform an update query or another query?

Can I copy the results into another store key?

Ps: sorry for that weird title. Was writing on tablet and accidentally hit return. Any help is great,y appreciated.

**Comment by stubailo** [comment]
Hey, thanks for asking - I've heard several people talking about using redux-form, so we should have something that documents how to do that directly.

> My issue is, that form values need to be preloaded from the store.

Can you link me to some directions of how redux-form says one should do this? It would be helpful to take a look before making a specific suggestion.

**Comment by tomitrescak** [comment]
@stubailo the project is really nicely documented. The data preload from the store can be found here http://redux-form.com/5.2.3/#/examples/initializing-from-state?_k=y0vyu4

Basically, I need to point the redux-form to a specific key in the store. All the rest is done automatically.

**Comment by stubailo** [comment]
I see the problem here - both Apollo Client and Redux Form are introducing their own versions of `mapStateToProps` to do nice things for you.

I think if we have something like https://github.com/apollostack/apollo-client/issues/225, it will be much easier. Then we can just do something like:

```
state => {
  const data = apolloClient.readQueryFromState({ state, query });

  // convert data into initial values...

  return {
    initialValues,
  };
}),
```

Until then, I think you can also pass `initialValues` as a prop. So you should be able to use Apollo Client `connect` to get some props, and pass those into the redux form container. But the approach above would be a bit more idiomatic.

**Comment by jbaxleyiii** [comment]
This should be possible after #29

**Comment by tomitrescak** [comment]
@jbaxleyiii I went through the the whole discussion and a discussion on the related PR and I don't e see the possibility to copy the result into another point in store :/ only to reshape the result for the current component. This still will not work with optimistic updates. PR looks good though! Only this I see probkematic is that if I run 5-6 queries on a component and 4-5 mutations I get layering of 10+ components, but I guess that is an extreme case (that happens to me;)

**Comment by stubailo** [comment]
Agreed, we need a pattern to copy data from Apollo Client results into a different redux key. I think it's basically just `client.query(...).then((result) => { dispatch({ type: 'MY_ACTION', result }) })` but let's make sure we have something that feels nice to use since I hear about Redux Form a lot.

**Comment by jbaxleyiii** [comment]
@tomitrescak @stubailo I'm pretty sure this can be done without any changes to the client. Check out this PR: https://github.com/apollostack/react-apollo/pull/136
